# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UpcomingMovies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UpcomingMovies

    pod 'ObjectMapper', '~> 2.2'
    pod 'RxCocoa', '~> 3.4'
    pod 'RxSwift', '~> 3.4'
    pod 'AwesomeCache', '~> 5.0'
    pod 'SDWebImage', '~> 4.0'

end
